version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: transferapp
    container_name: transferapp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
        - .:/var/www
    networks:
      - transferapp-network
  mysqlsrv:
    image: mysql:5.7
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: "MySql2019!"
        MYSQL_DATABASE: "testedb"
    ports:
        - "3306:3306"
    volumes:
        - /cygdrive/c/Users/enio/projetos/tranferApp/MySql:/var/lib/mysql
    networks:
        - transferapp-network
  adminer:
    image: adminer
    ports:
        - "8080:8080"
    networks:
        - transferapp-network
  nginx:
    image: nginx:alpine
    container_name: transferapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - transferapp-network

networks:
  transferapp-network:
    driver: bridge